### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by janami1991** [timroemisch/mqtt-s7-connector#2]
I don't know, where to find the path to the configuration directory :-(
----------------------------------------------------------------------------------------------
Config File
The configuration file has to be located in the same directory as the installation and has to be named config.json

e.g. NPM global installation path: ****/usr/lib/node_modules/s7-mqtt-connector/config.json****

----------------------------------------------------------------------------------------------

thank you for your response
M.

**Comment by timroemisch** [comment]
Did you install it with npm or docker ?
